ErrorMsg      DB  'Library already initialized     '          ;  0
              DB  '386 or better CPU not found     '          ;  1
              DB  'No EMM driver detected          '          ;  2
              DB  'Not enough free EMS memory      '          ;  3
              DB  'Unable to open file             '          ;  4
              DB  'General file reading error      '          ;  5
              DB  'Blender map already allocated   '          ;  6
              DB  'Not enough free base memory     '          ;  7
              DB  'Blender map is not active       '          ;  8
              DB  'Cannot create file              '          ;  9
              DB  'General file writing error      '          ; 10
              DB  'Unknown or bad file format      '          ; 11
              DB  'No sounds initialized           '          ; 12
              DB  'DMA channel not supported       '          ; 13
              DB  'Failed to reset sound card DSP  '          ; 14
              DB  'High mixing speed not supported '          ; 15
              DB  'Old sound card not supported    '          ; 16
              DB  'File format not supported       '          ; 17
              DB  'Sound exceed 64k size limit     '          ; 18
              DB  'Unknown sound slot              '          ; 19
              DB  'Cannot read past end of file    '          ; 20
              DB  'Can',27h,'t open two FLI files at once'    ; 21
              DB  'Incompatible blender map        '          ; 22
              DB  'BLASTER variable not set        '          ; 23
              DB  'Sound engine not yet initialized'          ; 24
              DB  'Datafile not yet opened         '          ; 25
              DB  'Unknown packet ID               '          ; 26
              DB  'Bad password or corrupted data  '          ; 27
              DB  'Can',27h,'t open two datafiles at once'    ; 28
              DB  'Operation successful            '          ; 29
